### PR TITLE
implemented @Fobermaier's suggestions

### PR DESCRIPTION
**Pull request by jaundice**

### CODE REVIEW

**Comment by FObermaier** [comment]
If you don't mind @jaundice, I'll adjust some namespaces

**Comment by jaundice** [comment]
Sure



Sent from my Samsung device


-------- Original message --------

**Comment by FObermaier** [comment]
@jaundice: could you please have a look at 9bd7b3b29a93b98bfe7c3586149bbd904c8dfec2

**Comment by jaundice** [comment]
Looks fine to me. Perhaps we should move NetTopologySuite.IO.Shapefile.Extended.CloudStorage to NetTopologySuite.IO.Streams.CloudStorage

**Pull request merged**
