### PR TITLE
Fix xml code documentation flaws

### PR DESCRIPTION
**Pull request by FObermaier**

### CODE REVIEW

**Comment by DGuidi** [comment]
not sure about latest commit you made...
`<value>` tag is used as return value in properties, at least according to [xml specs](https://docs.microsoft.com/it-it/dotnet/csharp/codedoc)

> The **value** tag is similar to the **returns** tag, except that you use it for properties

where `<c>` is used to mark part of the docs as **code**

**Comment by FObermaier** [comment]
@DGuidi but `<value>` was used at other places, too. These were changed.

**Comment by DGuidi** [comment]
My bad

**Comment by DGuidi** [comment]
today it's definitively not my day...

**Pull request merged**
