### PR TITLE
KdTree patch

### PR DESCRIPTION
**Pull request by DGuidi**
Applied KdTree patch from #97

### CODE REVIEW

**Comment by DGuidi** [comment]
@ikolev21 feel free to add your feelings here

**Comment by ikolev21** [comment]
Thanks, the patched stuff looks OK.

Now a couple of new comments :)
Look at line 196 that was commented out, `//if (currentNode != null) same check as in "while loop"`
I think this check was originally meant to be `if (_tolerance > 0)`.
Currently passing tolerance 0 to the tree doesn't work as expected because this check is missing, i.e. the tree will still merge points that have exactly the same coordinates, while the idea of tolerance 0 is to never merge points, even if coinciding.

The other comment is that the tolerance check can be made faster if the square of `_tolerance` is stored and comparison calculates just the squared distance instead of the exact one.

**Comment by DGuidi** [comment]
please check also [JTS implemetation](https://github.com/dr-jts/jts/blob/f6187ee22aee29933c561284e1cb56df32fddcc0/modules/core/src/main/java/org/locationtech/jts/index/kdtree/KdTree.java).
Actually, I'm ambivalent about this changes: I'd like to have NTS strictly matches JTS code. So, maybe this code can be also proposed to @dr-jts for JTS integration?
I'm adding too much partecipants to this pullreq?

**Comment by ikolev21** [comment]
I see that the JTS class misses the NearestNeighbor method, so our changes do not concern JTS.

As for `insertExact`, I think it has the same problem as NTS, the `if (currentNode != null) {` check must be changed to `if (tolerance > 0)`, to make tolerance==0 disable node merging.
The squared distance is less important, it's just a small performance optimization, but it still applies to JTS as well.

**Comment by DGuidi** [comment]
@FObermaier sorry to involve you, but can you help me with this?
as said [here](https://github.com/NetTopologySuite/NetTopologySuite/pull/105#issuecomment-210288484) I'm ambivalent about this integration, any suggestion from you is welcome.

**Comment by FObermaier** [comment]
As we have added this functionality in the first place, it should at least work alright.
Maybe we can refactor the code putting by putting the "non-JTS" portions in some partial class or make it an extension method.

IIRC I [submitted this enhancement to the mailing list](https://sourceforge.net/p/jts-topo-suite/mailman/message/34889739/). No response however.

**Comment by DGuidi** [comment]
thx, missed submission to jts mailing list.

**Comment by DGuidi** [comment]
I've made KdTree class abstract, with two different implementation for JTS (close to java code) and NTS (with fixes). If we like this changes, I'm ready to merge code.

**Comment by FObermaier** [comment]
I don't like two implementations.
I checked, both splitting the source file and making `NearestNeighbor` an extension method to KdTree works. For the later we'll have to expose `_root` but that should not pose any probems.

**Comment by DGuidi** [comment]
ah ok, made same changes. no prob.

**Pull request closed without merging**
