### PR TITLE
Remove remaining mentions of PowerCollections

### PR DESCRIPTION
**Pull request by airbreather**
This refers to:

1. Everything that came up in a full search for "PowerCollections", **except** the license stuff.
2. A few `using` aliases for `HashSet<T>` that didn't need to exist anymore.

### CODE REVIEW

**Comment by FObermaier** [comment]
@airbreather, @DGuidi 
I think this is it. Could you please review the additions I made to the license information?
Thanks @airbreather  for pushing this.

**Comment by airbreather** [comment]
@FObermaier: RevSnipplets looks good to me now.  Builds OK from scratch.  License file meets what I expected.  Tests in NUnit and NUnit.Pcl that I was able to run seem to pass.

**Comment by DGuidi** [comment]
ok I proceed to integration

**Comment by DGuidi** [comment]
branch __revsnipplets__ merged, hope I' haven't made any mistake

**Pull request merged**
