### PR TITLE
Added basic contributor guidelines.

### PR DESCRIPTION
**Pull request by xivk**
I added contributor guidelines to make sure contributions are easier in the future but they are incomplete.

Asking @FObermaier, @DGuidi and others to help specify how the relation with JTS works.

### CODE REVIEW

**Comment by xivk** [comment]
Feel free to add that, I just think we should keep it short to make sure people actually read it or parts of it! :-)

I was also looking for feedback on this part:

https://github.com/NetTopologySuite/NetTopologySuite/pull/173/commits/fcbdba4373af513dd187020d28f052541756dc8d#diff-6a3371457528722a734f3c51d9238c13R14

I know there are projects that aren't mirrors of JTS, it's also important to know that before adding new stuff. Do you know what projects are mirrors and what projects are not?

**Comment by xivk** [comment]
I also suggest adding a fancy icon to the github organization and the nuget packages, here are a few options:

- https://thenounproject.com/term/polygon/17101/
- https://thenounproject.com/term/shapes/104967/
- https://thenounproject.com/term/shapes/40426/

Makes the project more recognizable and not look like any other package out there.

**Comment by FObermaier** [comment]
There is a [Contribution wiki page](https://github.com/NetTopologySuite/NetTopologySuite/wiki/Contribution) present. This should be merged, at least not diverge.

**Comment by xivk** [comment]
Ok did not know that! 👍 I would still recommend keeping this one because it shows up before submitting pull-requests or issues on github:

https://github.com/itinero/routing/issues/new

**Comment by xivk** [comment]
Merged in what's being said on the wiki, we should remove that page once this is merged.

**Comment by DGuidi** [comment]
go with this, we can easily add other stuff later

**Comment by FObermaier** [comment]
`NetTopologySuite.IO.GeoJSON` is ours. The GeoJSON IO stuff in `JTS` only covers the geometry part.
The `NetTopologySuite.Features` namespace is non-existant in `JTS`.

**Comment by xivk** [comment]
I added an icon to the NTS organization, let me know if anyone objects to this... or wants something else.

**Comment by DGuidi** [comment]
looks like a pirate :)

**Comment by xivk** [comment]
Yeah, it kind of does... ;-) It's supposed to be a map, feel free to suggest something else! 👍

**Pull request merged**
